blog:
  build: ./
  volumes:
   - ./logs/:/var/log/apache2/
   - ./www/:/var/www/
#   - ./auryn/defaultApacheConfig:/var/www/defaultApacheConfig
   - ./dns/hosts:/etc/hosts
   - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
  environment:
    XDEBUG_CONFIG: remote_host=172.17.0.1