php:
  image: blog
  build: ./
  ports:
   - "80:80"
   - "443:443"
#   not working
#  volumes:
#   - /var/www/:/auryn/www3/
#   - logs/:/var/log/apache2/
  environment:
    XDEBUG_CONFIG: remote_host=10.254.254.254