version: '2'
services:
  blog:
    build: ./
    ports:
       - "80:80"
       - "443:443"
       - "2200:22"
    volumes:
     - ./logs/:/var/log/apache2/
     - ./auryn/defaultApacheConfig:/var/www/defaultApacheConfig
     - DataVolume1:/var/www
    environment:
      XDEBUG_CONFIG: remote_host=10.254.254.254
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - PMA_ARBITRARY=1
      restart: always
      ports:
       - 8081:80
volumes:
  DataVolume1: