version: '2'
services:
  blog:
    container_name: blog
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - REMOTE_HOST="${IP_HOST}"
    ports:
       - "80:80"
       - "443:443"
       - "2200:22"
    volumes:
     - ./logs/:/var/log/apache2/
     - ./auryn/defaultApacheConfig:/var/www/defaultApacheConfig
     - ./www:/var/www
     - ./renderedImages/:/renderedImages/
    environment:
      XDEBUG_CONFIG: remote_host=${IP_HOST}
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - PMA_ARBITRARY=1
      restart: always
      ports:
       - 8081:80